### ISSUE TITLE
Register.js, submit and redirect

### ISSUE THREAD

**Issue by jeff-bothe** [joeEscob1023/simpleloginform#1]
Saw your post on facebook, responding here:

So, when troubleshooting a problem, I always try to find a solution with HTML first, before looking for JS or React or third-party library solutions. Solid, semantic, plain HTML is the foundation of good websites, and learning it deeply will prevent headaches from scrambling to find JS hacks for stuff that is built into HTML natively.

The main problem I see with this code is that, where you have a `<Button />` component, you should have a plain HTML `<input type="submit" />` element instead.  This renders a button-like input element, that when clicked will submit the form, calling the form's `onSubmit` handler. I have a feeling you don't know about this element, cuz in your comments you mentioned putting the `onSubmit` handler on the button, which is definitely not what you want to do. `onSubmit` always goes on the form.

so, at bare minimum, you could try replacing line 31 with: 

```
<input type="submit" />
```

I am not entirely sure the above solution will work, cuz I don't know what kind of behavior to expect from an `<input />` element inside of a `<Link />`. But more importantly, it is bad HTML practice to put a button or an input inside of a link.

Taking it a step further, what I would do is get rid of the `<Link />`, and try one of two things:

1. Modify the `render()` function so that it renders a `<Redirect />` component (provided by the react-router library) if `props.loggedIn` is true. In other words, add this line at the very top of the render function:

```
if (this.props.loggedIn) return <Redirect to="/Profile" />
```

You also have to import Redirect from react-router or react-router-dom or wherever it comes from, i don't remember but you can look that up.

2. The other option would be to use `props.history.push`, but thats more complicated and I don't feel like writing about it right now. Hahaha. also, probably not necessary. Let me know how this other solutions turn out.

Fun fact! Using `<input type-"submit" />` give you a keypress event listener for free! When you have focus on any of the input elements of the form, pressing `enter` will submit the form :)

Oh! almost forgot, on line 17 you dont need to make a new inline function for the `onSubmit` handler. Its ok just to have `onSubmit={this.props.onSubmit}`. The event object (which you have named `e`), is always passed to event handlers. This is true of event handlers inlined in plain HTML, and also even handlers passed as callbacks to the plain JavaScript `addEventListener` function.

**Comment by joeEscob1023** [comment]
Im trying the redirect right now and it is not working. the state of loggedIn is true, but it is still stuck on the register component rather than the profile component. Its not even reaching the if statement and the code below is coming from the Register component.
 ```   
        render() {
       f(this.props.loggedIn) {
       return <Redirect to='/Profile' />
        console.log(this.props.loggedIn)
    }

    return (
      <div>
        <h1 className="mb-5">Please Sign Up or Login</h1>
        
        <Form className="w-50 mx-auto">
          <FormGroup>
            <Label for="name">Name</Label>
            <Input type="text" name="name" id="name" required placeholder="Enter Your name" onChange={this.props.onChange}/>
          </FormGroup>
          <FormGroup>
            <Label for="email">Email</Label>
            <Input type="email" name="email" id="email" required placeholder="please enter email" onChange={this.props.onChange} />
          </FormGroup>
          <FormGroup>
            <Label for="examplePassword">Password</Label>
            <Input type="password" name="password" id="password" required placeholder="password " onChange={this.props.onChange}/>
          </FormGroup>
          {/* <Link to="/Profile"> */}
            <input  onClick={ this.props.onSubmit} type="submit" className="btn btn-primary" color="dark" dark="true" block="true" />
          {/* </Link> */}
        </Form>
      </div>
    )
  }
}
```

**Comment by jeff-bothe** [comment]
hmmmmm, for one thing, it looks like you have a typo. You forgot the letter 'i' in 'if'.

Also, in App.js, it looks like you are not passing `state.loggedIn` into the Register component.

Try this:

```
<Route
  exact path='/'
  render={(props) => <Register {...props} loggedIn={this.state.loggedIn} onSubmit={this.onSubmit} onChange={this.onChangeHandler} />}
/>
```

Tip: You would be more successful debugging the component if you moved the console.log statement outside the `if` block.

**Comment by joeEscob1023** [comment]
I have basically the the same code in my onSubmit, its supposed to change the state to true when its clicked which it does, but it doesnt redirect, i the only difference in my onSubmit is that there is an if statement that says if its the state is false, when clicked make it true. Im having the hardest time figuring out something that is probably really easy..

**Comment by joeEscob1023** [comment]
I cant even open the code now.. for some reason im getting an error saying operation not permitted and locked up my components..
